- CHANGELOG.md
- src/lib/pages/instantiate/component/InstantiateOffchainForm.tsx
- src/lib/pages/past-txs/query/generateWhere.ts
- src/lib/services/amplitude.tsx
Past tx page should support only wasm and send message
> fix: past tx page should support only wasm and send msg

- CHANGELOG.md
- src/lib/services/publicProjectService.ts
- src/lib/types/projects.ts
Fix contract count for code table in public project
> fix: contract count for code table in public project

- CHANGELOG.md
- package.json
- src/lib/app-provider/hooks/useAmplitude.ts
- src/lib/hooks/useLCDEndpoint.ts
- yarn.lock
- remove `window.crypto.randomUUID()` and use from `uuid.v4()`
- fix `array.at()` in `useLCDEndpoint`
- go to query or execute page on safari
> fix: uuid in old safari version

- CHANGELOG.md
- src/lib/components/modal/contract/SaveNewContract.tsx
- src/lib/pages/instantiate/instantiate.tsx
- src/lib/pages/migrate/components/MigrateContract.tsx
- Fix state reset in Save New Code modal and no permission in migration
> fix: state reset in save new code

- CHANGELOG.md
- src/lib/app-provider/hooks/index.ts
- src/lib/app-provider/hooks/useCurrentNetwork.ts
- src/lib/components/button/BackButton.tsx
- src/lib/components/button/FaucetButton.tsx
- src/lib/components/button/index.ts
- src/lib/components/forms/TextInput.tsx
- src/lib/hooks/useToast.ts
- src/lib/layout/Header.tsx
- src/lib/pages/deploy/index.tsx
- src/lib/pages/faucet/index.tsx
- src/lib/services/amplitude.tsx
- src/lib/styles/theme/colors.ts
- src/lib/styles/theme/components/alert.ts
- src/pages/[network]/faucet.tsx
- src/pages/faucet.tsx
- add Faucet for requesting Testnet OSMO (Testnet only)
> Add Faucet page

- CHANGELOG.md
- src/lib/layout/navbar/index.tsx
- Add condition check for a home route without network param on isCurrentPage function.
> Fix incorrect isCurrentPage for overview page

- CHANGELOG.md
- src/lib/pages/instantiate/instantiate.tsx
- Fix json funds instantiate cannot edit because there is some `state` in dependency array.
> Fix json funds cannot update on instantiate page

- CHANGELOG.md
- src/lib/components/table/codes/CodesTable.tsx
- src/lib/components/table/contracts/ContractsTable.tsx
- src/lib/components/table/proposals/ProposalsTable.tsx
- src/lib/components/table/transactions/TransactionsNoSenderTable.tsx
- src/lib/components/table/transactions/TransactionsTable.tsx
- Fix table padding bottom for editable cells
> fix: table pb

- CHANGELOG.md
- src/lib/components/ContractSelectSection.tsx
- src/lib/components/ExplorerLink.tsx
- src/lib/components/TokenCard.tsx
- src/lib/components/action-msg/ActionMessages.tsx
- src/lib/components/action-msg/SingleActionMsg.tsx
- src/lib/components/action-msg/SingleMsg.tsx
- src/lib/components/copy/Copier.tsx
- src/lib/components/modal/UnsupportedTokensModal.tsx
- src/lib/components/select-contract/ContractListTable.tsx
- src/lib/components/table/AccordionTx.tsx
- src/lib/components/table/codes/CodesTableRow.tsx
- src/lib/components/table/contracts/ContractsTableRow.tsx
- src/lib/components/table/proposals/ProposalsTableRow.tsx
- src/lib/components/table/transactions/TransactionsTableRow.tsx
- src/lib/pages/code-details/components/CodeInfoSection.tsx
- src/lib/pages/codes/components/CodesTable.tsx
- src/lib/pages/contract-details/components/InstantiateInfo.tsx
- src/lib/pages/contract-details/components/tables/migration/MigrationRow.tsx
- src/lib/pages/home/components/RecentActivities.tsx
- src/lib/pages/past-txs/components/PastTxRow.tsx
- src/lib/pages/public-project/components/table/code/PublicProjectCodeRow.tsx
- src/lib/pages/public-project/components/table/contract/PublicProjectContractRow.tsx
- src/lib/styles/globals.css
- Refactor hover logic of copier icon
> refactor: copier hover logic

- CHANGELOG.md
- src/lib/pages/contract-details/components/InstantiateInfo.tsx
Fix address type render text for admin address in contract details page
> fix(components): fix admin address type text render

- CHANGELOG.md
- src/lib/app-provider/hooks/useAddress.ts
- src/lib/components/ExplorerLink.tsx
- src/lib/components/TokenCard.tsx
- src/lib/components/ViewPermissionAddresses.tsx
- src/lib/components/copy/Copier.tsx
- src/lib/components/copy/CopyButton.tsx
- src/lib/components/icon/CustomIcon.tsx
- src/lib/components/json/JsonReadOnly.tsx
- src/lib/components/modal/CodeSnippet.tsx
- src/lib/components/modal/UnsupportedTokensModal.tsx
- src/lib/pages/code-details/components/CodeInfoSection.tsx
- src/lib/pages/contract-details/components/TokenSection.tsx
- src/lib/pages/execute/components/ExecuteArea.tsx
- src/lib/pages/instantiate/component/FailedModal.tsx
- src/lib/pages/query/components/QueryArea.tsx
- src/lib/pages/tx-details/components/MessageSection.tsx
- src/lib/pages/tx-details/components/TxHeader.tsx
- src/lib/pages/tx-details/components/TxInfo.tsx
- src/lib/pages/tx-details/components/tx-message/EventBox.tsx
- src/lib/pages/tx-details/components/tx-message/TxMsgExpand.tsx
- src/lib/pages/tx-details/components/tx-message/index.tsx
- src/lib/pages/tx-details/components/tx-message/msg-receipts/CoinComponent.tsx
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
- src/lib/pages/tx-details/components/tx-message/msg-receipts/renderUtils.tsx
- src/lib/pages/tx-details/index.tsx
- src/lib/services/amplitude.tsx
- src/lib/styles/theme/components/badge.ts
- src/lib/utils/tx/types.ts
1. Add amplitude tracking
2. Components bug fixes
> Tx amplitude

- CHANGELOG.md
- src/lib/services/tx.ts
> fix: txhash uppercase query

- CHANGELOG.md
- src/lib/components/filter/FilterChip.tsx
- src/lib/components/filter/FilterComponents.ts
- src/lib/components/filter/FilterDropdownItem.tsx
- src/lib/components/filter/FilterInput.tsx
- src/lib/components/table/proposals/ProposalsTableRow.tsx
- src/lib/components/table/proposals/ResolvedHeight.tsx
- src/lib/components/table/proposals/StatusChip.tsx
- src/lib/components/table/proposals/VotingEndTime.tsx
- src/lib/gql/gql.ts
- src/lib/gql/graphql.ts
- src/lib/pages/proposals/components/ProposalStatusFilter.tsx
- src/lib/pages/proposals/components/ProposalTypeFilter.tsx
- src/lib/pages/proposals/index.tsx
- src/lib/pages/proposals/table/ProposalTableRow.tsx
- src/lib/query/proposal.ts
- src/lib/services/expression/proposalExpression.ts
- src/lib/services/proposalService.ts
- src/lib/types/proposal.ts
- src/lib/utils/index.ts
- src/lib/utils/proposal.ts
- Add filter by status and type to proposal list page
- Change Inactive proposal status to deposit failed
- Proposal types are queried from graphql
> feat: add filters to proposal list page

- CHANGELOG.md
- src/lib/gql/gql.ts
- src/lib/gql/graphql.ts
- src/lib/pages/blocks/components/BlocksHeader.tsx
- src/lib/pages/blocks/components/BlocksRow.tsx
- src/lib/pages/blocks/components/BlocksTable.tsx
- src/lib/pages/blocks/index.tsx
- src/lib/query/block.ts
- src/lib/services/blockService.ts
- src/lib/types/block.ts
- src/lib/types/index.ts
- src/pages/[network]/blocks.tsx
- src/pages/blocks.tsx
> feat: (WIP) blocks page w/o proposer

- CHANGELOG.md
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
- src/lib/utils/tx/types.ts
> fix: fix begin unlocking optional coins field causing crash

- CHANGELOG.md
- src/lib/pages/blocks/components/BlocksTable.tsx
add data fetching error state, and empty state  to blocks page
> fix: add data fetching error state, and empty state  to blocks page

- CHANGELOG.md
- src/env.ts
- src/lib/app-provider/contexts/app.tsx
- src/lib/app-provider/hooks/useCelatoneApp.ts
- src/pages/_app.tsx
- src/types.ts
Add app default human address for each chain
> feat: add app default human address for each chain

- CHANGELOG.md
- src/lib/utils/formatter/token.ts
- Handle format token with M and show only 2 decimal points when more than 1,000
> feat: handle format M

- CHANGELOG.md
- src/lib/components/pagination/index.tsx
- src/lib/pages/network-overview/index.tsx
- add comma separator to pagination and block count
> chore: add comma to pagination, block count

- CHANGELOG.md
- src/lib/pages/account-details/components/asset/index.tsx
- src/lib/pages/account-details/components/delegations/index.tsx
- src/lib/pages/account-details/components/tables/AdminContractsTable.tsx
- src/lib/pages/account-details/components/tables/InstantiatedContractsTable.tsx
- src/lib/pages/account-details/components/tables/OpenedProposalsTable.tsx
- src/lib/pages/account-details/components/tables/StoredCodesTable.tsx
- src/lib/pages/account-details/components/tables/TxsTable.tsx
- src/lib/pages/account-details/index.tsx
> fix(components): fix account detail spacing

- CHANGELOG.md
- src/lib/pages/pools/components/unsupportedSection/UnsupportedPoolCard.tsx
- src/lib/pages/pools/components/unsupportedSection/UnsupportedPoolList.tsx
- src/lib/pages/pools/components/unsupportedSection/index.tsx
- Add expand/collapse all for unsupported pool list
> feat: add expand all

- CHANGELOG.md
- src/lib/components/TokenCard.tsx
> fix: show full number for token card

- CHANGELOG.md
- src/lib/pages/proposal/whitelist/index.tsx
> fix: trigger whitelist revalidation

- CHANGELOG.md
- src/lib/pages/account-details/components/tables/TxsTable.tsx
Pagination problem when using filter
> fix: pagination issue in txs table in account details

- CHANGELOG.md
- src/lib/app-fns/tx/clearAdmin.tsx
- src/lib/app-fns/tx/common/catchTxError.tsx
- src/lib/app-fns/tx/common/post.tsx
- src/lib/app-fns/tx/execute.tsx
- src/lib/app-fns/tx/migrate.tsx
- src/lib/app-fns/tx/resend.tsx
- src/lib/app-fns/tx/submitProposal.tsx
- src/lib/app-fns/tx/updateAdmin.tsx
- src/lib/app-fns/tx/upload.tsx
- src/lib/components/ExplorerLink.tsx
> fix: open new tab on tx modal link clicked

- CHANGELOG.md
> Remove wrong version on Changelog

- CHANGELOG.md
- src/lib/pages/proposal/utils/getAlert.tsx
- src/lib/pages/proposal/whitelist/index.tsx
- src/lib/services/delegation.ts
- src/lib/services/proposal.ts
- src/lib/services/proposalService.ts
- src/lib/types/converter.ts
- src/lib/types/index.ts
- src/lib/utils/date.ts
Show deposit/voting period from gov params and add minimum required alert
> feat: show deposit/voting period from gov params and add alert

- CHANGELOG.md
- src/lib/components/StopPropagationBox.tsx
- src/lib/components/table/proposals/VotingEndTime.tsx
- src/lib/pages/proposals/components/ProposalTextCell.tsx
- src/lib/pages/proposals/table/ProposalTableRow.tsx
> fix: proposal table component propagation

- CHANGELOG.md
- src/lib/pages/proposal/constants.tsx
- src/lib/pages/proposal/store-code/index.tsx
Add validation check for builder
> fix: add validation for builder

- CHANGELOG.md
- package.json
- src/env.ts
- src/lib/app-fns/explorer/index.ts
- src/lib/app-provider/hooks/useAddress.ts
- src/lib/app-provider/query-client/index.ts
- src/lib/data/chain.ts
- src/lib/layout/navbar/index.tsx
- src/lib/services/txService.ts
- src/pages/_app.tsx
- yarn.lock
- Change `osmo-test-4` to `osmo-test-5`
- Fix tx service to support address or accountId is undefined
> feat: change osmo-test-4 to osmo-test-5

- CHANGELOG.md
- src/lib/app-provider/contexts/app.tsx
- Stop propagation on beforeload event
> fix: stop propagration beforeunload event

- CHANGELOG.md
- src/lib/components/table/AccordionTx.tsx
- src/lib/components/table/transactions/TransactionsTableRow.tsx
Remove resend and redo button in accordion if relation is related (Past txs page)
> fix: remove resend and redo button in accordion if relation is related

- CHANGELOG.md
- src/lib/pages/proposal/components/AssetBox.tsx
- Add fallback N/A token image on AssetBox
> Add fallback N/A token on AssetBox

- CHANGELOG.md
- src/lib/pages/proposal/store-code/index.tsx
Fix enable tx bug in proposal to store code
> fix: any of addresses enable tx bug

- CHANGELOG.md
- update CHANGELOG.md for v1.0.5
> docs: update CHANGELOG.md for v1.0.5

- CHANGELOG.md
- src/config/index.ts
- src/config/types.ts
- src/lib/app-provider/hooks/index.ts
- src/lib/app-provider/hooks/useWasmConfig.ts
- src/lib/app-provider/tx/clearAdmin.ts
- src/lib/app-provider/types.ts
- src/lib/data/constant.ts
Use gas from chain config including default gas on clear admin page
> fix: use gas from chain config

- CHANGELOG.md
- src/lib/app-provider/hooks/useAddress.ts
- src/lib/components/modal/UnsupportedTokensModal.tsx
- src/lib/hooks/useSingleMessageProps.ts
- src/lib/pages/public-project/components/table/code/PublicProjectCodeRow.tsx
- src/lib/pages/public-project/components/table/contract/PublicProjectContractRow.tsx
> Use address type length from example addresses instead of hardcode

- CHANGELOG.md
- src/lib/pages/pools/components/supportedSection/index.tsx
- src/lib/pages/pools/components/unsupportedSection/index.tsx
- Fix supported pool list cannot be searched with token ID
> fix: unsupported pool search

- CHANGELOG.md
- src/lib/pages/pools/components/pool-details/tables/pool-txs/PoolTxsMsg.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/PoolTxsTableRow.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lockup/MsgLockTokensDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolAssetsGrid.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolLPCard.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/superfluid/MsgLockAndSuperfluidDelegateDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/components/PoolSwap.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/utils.ts
- Fix incorrect assigned message index for each pool message in pool tx tables
> fix: pool msg index

- CHANGELOG.md
- src/env.ts
- src/lib/app-fns/explorer/index.ts
- src/lib/components/modal/CodeSnippet.tsx
- Fix missed out hard-coded osmosis testnet 4 in code
> fix: missed out osmo 4

- CHANGELOG.md
- src/lib/services/contract.ts
Fix incorrect block_height and tx_index type in ContractResponse 
https://lcd.osmosis.zone/cosmwasm/wasm/v1/contract/osmo10vsjh59l8mpncmsl9hggf6ryxpf0kne09qa9wtn8j6ar3mh2mdlsq9h7dh
> fix: contractResponse type

- CHANGELOG.md
- src/config/index.ts
- src/config/types.ts
- src/lib/components/Meta.tsx
- src/lib/components/Seo.tsx
- Use chain name from config for Meta instead of env variable
> feat: meta from config

- CHANGELOG.md
- src/lib/app-provider/hooks/useWasmConfig.ts
- src/lib/pages/contracts/index.tsx
- src/lib/pages/proposal/constants.tsx
- src/lib/pages/proposal/store-code/index.tsx
- src/lib/pages/proposal/whitelist/index.tsx
Fix bug found in local support 2 branch
including
- title input field in `/proposals/store-code`
- navigation in sticky bar in `/proposals/store-code`
- redirect path when wasm flag is disable `/contracts` ,` /proposals/store-code`, `/proposals/whitelist`
> fix: bug in local-support-2

- CHANGELOG.md
- src/lib/data/tx.ts
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
- src/lib/utils/tx/types.ts
> feat: add pool manager v15 msgs to tx details

- CHANGELOG.md
- src/lib/pages/account-details/index.tsx
> fix: handle uppercase address

- src/lib/pages/admin/index.tsx
- src/lib/pages/deploy/index.tsx
- src/lib/pages/migrate/components/MigrateOptions.tsx
- src/lib/pages/migrate/index.tsx
- src/lib/pages/my-codes/components/MyStoredCodesSection.tsx
- src/lib/pages/proposal/constants.tsx
- src/lib/pages/proposal/whitelist/index.tsx
- src/pages/_app.tsx
> fix: fix rpc/lcd provider, tweak whitelist msg permission, etc

- CHANGELOG.md
- src/lib/pages/account-details/index.tsx
- src/lib/services/codeService.ts
- src/lib/services/contractService.ts
- Disable wasm related tabs on the account detail page
> fix: disable wasm on account detail

- CHANGELOG.md
- src/lib/pages/block-details/components/BlockDetailsTop.tsx
> refactor: use internal navigate instead of app link for block navigation

- README.md
1. Add nvm instruction
2. Change `Yarn` url
> Update local support readme

- CHANGELOG.md
- src/lib/components/dropzone/index.tsx
- Add code upload error message under the dropzone
> feat: upload code err msg

- CHANGELOG.md
- package.json
- src/lib/utils/date.test.ts
- src/lib/utils/date.ts
- yarn.lock
> test: add test cases for date utils

- .gitignore
- CHANGELOG.md
- package.json
> feat: add gitignore for new yarn version

- CHANGELOG.md
- src/lib/gql/gql.ts
- src/lib/gql/graphql.ts
- src/lib/query/validator.ts
- src/lib/services/validator.ts
- src/lib/services/validatorService.ts
- src/lib/types/validator.ts
- Get all validators from graphql
> feat: validator list from gql

- CHANGELOG.md
- src/lib/app-provider/hooks/useBaseApiRoute.ts
- src/lib/components/table/TableTitle.tsx
- src/lib/model/account.ts
- src/lib/model/contract.ts
- src/lib/pages/account-details/components/mobile/MobileTitle.tsx
- src/lib/pages/account-details/components/tables/txs/TxsTable.tsx
- src/lib/pages/account-details/index.tsx
- src/lib/pages/past-txs/index.tsx
- src/lib/pages/public-project/components/table/account/PublicProjectAccountTable.tsx
- src/lib/pages/public-project/components/table/code/PublicProjectCodeTable.tsx
- src/lib/pages/public-project/components/table/contract/PublicProjectContractTable.tsx
- src/lib/services/accountService.ts
- src/lib/services/expression/txExpression.ts
- src/lib/services/proposal.ts
- src/lib/services/proposalService.ts
- src/lib/services/txService.ts
Fix upload access endpoint, Public project searchbar bug, account tx bug
> fix upload access endpoint, public project searchbar bug, account tx

- src/lib/components/StickySidebar.tsx
- src/lib/pages/account-details/components/mobile/MobileLabel.tsx
- src/lib/pages/public-project/components/AllProject.tsx
- src/lib/styles/theme/components/accordion.ts
> fix(components): fix accordion

- CHANGELOG.md
- src/lib/components/select-contract/ContractListDetail.tsx
loading stuck incorrectly for other folder other than instantiated by me
> fix: fix contract selection loading state for other folders

- CHANGELOG.md
- src/lib/components/CustomTab.tsx
- src/lib/pages/pools/components/pool-details/PoolRelatedTxs.tsx
- src/lib/pages/pools/data.ts
> fix: pool count chip

- CHANGELOG.md
- src/lib/components/StickySidebar.tsx
- src/lib/components/button/NewProposalButton.tsx
- src/lib/pages/proposal/store-code/index.tsx
- src/lib/pages/proposal/whitelist/index.tsx
- src/lib/styles/theme/components/alert.ts
> fix(components): add alert for forum review in proposal store code page

- CHANGELOG.md
- src/lib/pages/contract-details/components/tables/TxsTable.tsx
- src/lib/pages/contract-details/index.tsx
> fix: change contract addr to id in contract txs

- CHANGELOG.md
- src/lib/pages/blocks/components/BlocksTable.tsx
- src/lib/services/validatorService.ts
> fix: validator image

- CHANGELOG.md
- src/lib/services/faucetService.ts
- add `assetInfos` to `useFaucetInfo`'s dependencies.
> fix: wrong denom in faucet

- CHANGELOG.md
- src/lib/services/validatorService.ts
> fix: wrong access queryKey in validator info

- CHANGELOG.md
- src/lib/layout/SubHeader.tsx
> fix(components): fix developer mode alert styling

- CHANGELOG.md
- src/config/chain/default.ts
- src/config/chain/index.ts
- src/config/chain/neutron.ts
- src/config/chain/osmosis.ts
- src/config/chain/sei.ts
- src/config/chain/stargaze.ts
- src/config/chain/terra.ts
- src/config/chain/types.ts
- src/env.ts
- src/lib/app-provider/contexts/app.tsx
- src/lib/app-provider/hooks/useConfig.ts
- src/lib/chain-registry/terra2testnet.ts
- src/lib/components/button/NewProposalButton.tsx
- src/lib/layout/SubHeader.tsx
- src/lib/pages/proposals/index.tsx
- src/lib/pages/stored-codes/index.tsx
- src/lib/providers/cosmos-kit.tsx
- add govConfig
- add disableOpenProposal
- add disableProposetoStore
- add skeleton while permission is fetching on my stored codes
> Add gov configuration

- CHANGELOG.md
- src/config/chain/terra.ts
> Fix chain rpc

- CHANGELOG.md
- src/lib/pages/pools/components/pool-details/tables/pool-txs/PoolTxsMsg.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/PoolTxsTable.tsx
> fix(components): fix pool txs icon and style

- CHANGELOG.md
- src/config/chain/stargaze.ts
> feat: add stargaze testnet support

- CHANGELOG.md
- src/lib/app-fns/tx/execute.tsx
- src/lib/app-provider/tx/execute.ts
- src/lib/components/ContractSelectSection.tsx
- src/lib/components/InputWithIcon.tsx
- src/lib/components/copy/CopyButton.tsx
- src/lib/components/copy/CopyTemplate.tsx
- src/lib/components/json-schema/MessageInputSwitch.tsx
- src/lib/components/json-schema/form/index.tsx
- src/lib/components/modal/CodeSnippet.tsx
- src/lib/hooks/useQueryCmds.ts
- src/lib/pages/execute/components/ExecuteArea.tsx
- src/lib/pages/query/components/JsonQuery.tsx
- src/lib/pages/query/components/QueryArea.tsx
- src/lib/pages/query/components/SchemaQuery.tsx
- src/lib/pages/query/index.tsx
- src/lib/services/contractService.ts
- src/lib/stores/contract.ts
- src/lib/stores/schema-test-suite/query-schema-output.json
- src/lib/stores/schema.test.ts
- src/lib/stores/schema.ts
> feat: query json schema feat, pending schema response style config

- src/config/chain/default.ts
- src/config/chain/index.ts
- src/config/chain/initia.ts
- src/config/chain/neutron.ts
- src/config/chain/osmosis.ts
- src/config/chain/sei.ts
- src/config/chain/stargaze.ts
- src/config/chain/terra.ts
- src/config/chain/types.ts
- src/config/theme/index.ts
- src/config/theme/initia.ts
- src/env.ts
> feat(components): add initia theme

- CHANGELOG.md
- src/lib/components/TxFilterSelection.tsx
- src/lib/components/action-msg/MsgToken.tsx
- src/lib/components/action-msg/MultipleActionsMsg.tsx
- src/lib/components/action-msg/SingleMsg.tsx
- src/lib/components/table/transactions/TransactionsTable.tsx
- src/lib/pages/tx-details/components/tx-message/TxMsgExpand.tsx
> fix(components): adjust text size consistency in txs message

- CHANGELOG.md
- src/lib/pages/query/components/SchemaQuery.tsx
> fix: improve scrolling into view by delaying scroll function

- CHANGELOG.md
- src/lib/components/json-schema/MessageInputContent.tsx
- src/lib/pages/execute/components/ExecuteArea.tsx
- src/lib/pages/execute/components/JsonExecute.tsx
- src/lib/pages/execute/components/MsgSuggestion.tsx
- src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
- src/lib/pages/execute/components/schema-execute/index.tsx
- src/lib/pages/execute/index.tsx
- src/lib/pages/query/components/QueryArea.tsx
- src/lib/pages/query/components/SchemaQuery.tsx
- src/lib/stores/schema.ts
- add JSON schema on execute page
> Feat: Add Json schema on execute page

- CHANGELOG.md
- src/lib/components/json-schema/EditSchemaButtons.tsx
- src/lib/components/json-schema/JsonSchemaDrawer.tsx
- src/lib/components/json-schema/UploadTemplate.tsx
- src/lib/components/json-schema/form/widgets/SelectWidget.tsx
- src/lib/components/json-schema/index.ts
- src/lib/pages/code-details/components/json-schema/CodeSchemaSection.tsx
- src/lib/pages/contract-details/components/CommandSection.tsx
- src/lib/pages/contract-details/index.tsx
- src/lib/stores/schema.test.ts
- src/lib/stores/schema.ts
- Add jsonschema actions on contract detail page
> feat: schema actions on contract detail

- src/lib/pages/execute/components/ExecuteArea.tsx
- src/lib/pages/execute/index.tsx
- src/lib/pages/query/components/QueryArea.tsx
- src/lib/pages/query/index.tsx
> feat: support nullable schema

- CHANGELOG.md
- next.config.js
- src/lib/layout/SubHeader.tsx
- src/lib/pages/upload/completed.tsx
- Fix stored codes route and navbar behavior from dev to normal mode
> fix: storedcode and navbar dev to normal

- CHANGELOG.md
- src/lib/components/json-schema/UploadTemplate.tsx
- src/lib/components/json-schema/section/SchemaInputSection.tsx
- src/lib/pages/home/components/DevShortcut.tsx
- src/lib/pages/instantiate/instantiate.tsx
- src/lib/pages/migrate/components/MigrateContract.tsx
> fix: automatically switch to schema tab and show 404 not found error

- CHANGELOG.md
- src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
- src/lib/pages/query/components/SchemaQueryComponent.tsx
- src/lib/stores/schema-test-suite/query-schema-output.json
- src/lib/stores/schema-test-suite/schema-example.json
- src/lib/stores/schema.test.ts
- src/lib/stores/schema.ts
- src/lib/utils/json.ts
> fix: response Json schema UI

- CHANGELOG.md
- src/lib/components/forms/AssetInput.tsx
- src/lib/components/fund/index.tsx
- src/lib/components/fund/selectFund.tsx
> fix: adjust attach funds form label and icon styling for schema section

- CHANGELOG.md
- src/lib/app-provider/queries/simulateFee.ts
- src/lib/hooks/useExecuteCmds.ts
- src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
- src/lib/pages/execute/components/schema-execute/index.tsx
- fix simulation when user redo with initial message.
- change retry to false in execute cmds
- initial funds bug
> fix json schema simulation

- CHANGELOG.md
- src/lib/components/TxRelationSelection.tsx
- Fix tx relation selector incorrect option
> fix: tx relation selector

- CHANGELOG.md
- src/lib/pages/contract-details/components/tables/migration/MigrationRow.tsx
- src/lib/types/contract.ts
> fix: contract migration

- CHANGELOG.md
- src/lib/components/json-schema/form/index.tsx
- src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
- src/lib/pages/instantiate/instantiate.tsx
- validate when initialFormData has changed
> Validate when initialFormData has changed

- CHANGELOG.md
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
- Fix missing Tx proposal type
> fix: missing proposal type

- CHANGELOG.md
- src/lib/components/ExplorerLink.tsx
- src/lib/pages/blocks/components/BlocksRow.tsx
> fix: validator badge

- CHANGELOG.md
- src/lib/components/json-schema/UploadTemplate.tsx
> fix: refactor text

- CHANGELOG.md
- package.json
> docs: update after cut release v1.2.0

- CHANGELOG.md
- src/lib/pages/execute/components/JsonExecute.tsx
- src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
> fix: add attached funds to code snippet (to develop)

- CHANGELOG.md
- src/lib/pages/pools/components/PoolHeader.tsx
> fix(components): fix pool type alignment in pool card

- CHANGELOG.md
- src/lib/pages/home/components/DevShortcut.tsx
> fix(components): add move config to dev shortcuts

- CHANGELOG.md
- src/lib/hooks/useExecuteCmds.ts
- src/lib/hooks/useQueryCmds.ts
- src/lib/layout/navbar/index.tsx
- src/lib/pages/contract-details/components/CommandSection.tsx
feat: support contract from Sylvia
> Support Sylvia contract in message suggestion

- src/lib/components/MobileGuard.tsx
- src/lib/components/resource/ResourceDetailCard.tsx
- src/lib/layout/mobile/NavDrawer.tsx
> fix(components): adjust mobile guard

- CHANGELOG.md
- src/config/chain/initia.ts
- src/config/chain/osmosis.ts
> feat: add initia faucet

- CHANGELOG.md
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
- src/lib/utils/tx/types.ts
> feat: show parameter changes field for parameter change proposal tx

- src/lib/components/copy/CopyTemplate.tsx
- src/lib/components/modal/MoveCodeSnippet.tsx
- src/lib/components/modal/UnsupportedTokensModal.tsx
- Fix misaligned tooltip 
- Fix overlay code button
> Fix bug bash as comments

- CHANGELOG.md
- src/lib/components/token/TokenCard.tsx
- src/lib/components/token/TokenComposition.tsx
- src/lib/components/token/TokenImageRender.tsx
- src/lib/pages/account-details/components/delegations/DelegationsBody.tsx
- src/lib/pages/account-details/components/delegations/index.tsx
- src/lib/pages/account-details/components/tables/bonded/TokensCell.tsx
- src/lib/pages/account-details/components/tables/redelegation/RedelegationTableRow.tsx
- src/lib/pages/account-details/data.ts
- src/lib/services/poolService.ts
- src/lib/types/asset.ts
- src/lib/types/currency/balance.ts
- src/lib/utils/assetValue.ts
> (bugbash) fix: lp assets filtering and delegation ui/ux improvement

- CHANGELOG.md
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
> feat: display content field for submit proposal tx details

- CHANGELOG.md
- src/lib/components/copy/Copier.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/PoolTxsMsg.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/PoolTxsTable.tsx
- src/lib/pages/public-project/slug.tsx
fix pool txs row chevron and copy icon, add replace navigation option to public project details
> fix pool txs row and public project details navigation

- CHANGELOG.md
- package.json
- src/lib/components/abi/args-form/field/ArgFieldWidget.tsx
- src/lib/components/json-schema/form/templates/button-templates/icon-buttons/IconButton.tsx
- src/lib/components/json-schema/form/widgets/SelectWidget.tsx
- yarn.lock
> fix: downgrade version

- CHANGELOG.md
- src/lib/gql/fragment-masking.ts
- src/lib/gql/gql.ts
- src/lib/gql/graphql.ts
- src/lib/pages/tx-details/components/tx-message/msg-receipts/index.tsx
- src/lib/query/tx.ts
- src/lib/services/txService.ts
- src/lib/utils/extractMsgType.ts
- src/lib/utils/msgFurtherAction.ts
- src/lib/utils/tx/types.ts
- Dynamically change returned data of GraphQL that depends on `isWasm` and `isMove`
> Fix custom expression tx

- CHANGELOG.md
- src/lib/components/ExplorerLink.tsx
> fix: mintscan track

- CHANGELOG.md
- src/lib/layout/navbar/index.tsx
- src/lib/pages/saved-accounts/index.tsx
- src/lib/providers/store.tsx
- src/lib/stores/root.ts
- src/pages/[network]/saved-accounts.tsx
- src/pages/saved-accounts.tsx
> fix(components): add saved accounts page

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
- src/lib/components/modal/MoveCodeSnippet.tsx
> [to feat/initia]feat: deprecate stone-10

- CHANGELOG.md
- src/lib/layout/navbar/index.tsx
> fix: disable saved acc

- CHANGELOG.md
- src/lib/components/tx/TxReceiptRender.tsx
- src/lib/pages/tx-details/components/tx-message/TxMsgDetails.tsx
> fix: tx-ui-detail

- CHANGELOG.md
- src/lib/pages/pools/index.tsx
> fix: useEffect in pool page

- CHANGELOG.md
- src/lib/app-fns/tx/common/catchTxError.tsx
- src/lib/components/EstimatedFeeRender.tsx
- src/lib/components/table/contracts/TagsCell.tsx
- src/lib/layout/Searchbar.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lockup/MsgLockTokensDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolAssetsGrid.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolLPCard.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/superfluid/MsgLockAndSuperfluidDelegateDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/MsgSwapExactAmountInAction.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/MsgSwapExactAmountOutAction.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/MsgSwapExactAmountOutDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/components/PoolSwap.tsx
- src/lib/pages/tx-details/components/TxInfo.tsx
- src/lib/pages/tx-details/components/TxInfoMobile.tsx
- src/lib/pages/tx-details/components/tx-message/TxMsgExpand.tsx
- src/lib/services/contractService.ts
- src/lib/services/move/moduleService.ts
- src/lib/utils/codePermission.ts
- src/lib/utils/extractMsgType.ts
> fix: remove .at

- CHANGELOG.md
- src/config/project/index.ts
- src/config/project/types.ts
- src/lib/components/modal/ActionModal.tsx
- src/lib/components/modal/account/SaveNewAccount.tsx
- src/lib/components/modal/account/index.ts
- src/lib/hooks/useGetMaxLengthError.ts
- src/lib/hooks/useHandleSave.tsx
- src/lib/pages/saved-accounts/components/SaveAccountButton.tsx
- src/lib/pages/saved-accounts/index.tsx
- src/lib/providers/store.tsx
- src/lib/stores/account.ts
- src/lib/stores/root.ts
> fix(components): add saved accounts modal ui

- CHANGELOG.md
- src/lib/components/abi/args-form/field/utils/rules.ts
- src/lib/utils/abi.ts
> fix: abi empty vector

- CHANGELOG.md
- src/lib/components/abi/args-form/field/utils/rules.ts
- src/lib/utils/abi.ts
> [To Initia] fix: abi empty vector

- CHANGELOG.md
- src/lib/components/ValidatorBadge.tsx
- src/lib/services/validator.ts
> fix: val image

- CHANGELOG.md
- src/lib/amplitude/track-event/index.ts
- src/lib/amplitude/track-event/trackContractStates.ts
- src/lib/amplitude/types.ts
- src/lib/components/InputWithIcon.tsx
- src/lib/components/pagination/PageGoTo.tsx
- src/lib/components/pagination/PageList.tsx
- src/lib/pages/contract-details/components/contract-state/index.tsx
- src/lib/pages/contract-details/index.tsx
- add Amplitude for pagination, contract states and contract details
> feat(utils): amp contract states

- CHANGELOG.md
- package.json
> docs: cut release v1.3.0

- CHANGELOG.md
> docs: update for testing work pipeline

- CHANGELOG.md
- src/lib/layout/navbar/index.tsx
- src/lib/layout/navbar/utils.ts
> fix: this wallet navbar section

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> Feat: add stone 12 to main

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> feat: add stone-12 to develop

- CHANGELOG.md
- src/lib/layout/Header.tsx
- src/lib/layout/NetworkMenu.tsx
- src/lib/layout/mobile/NavDrawer.tsx
> fix: network menu

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
- src/lib/services/tx.ts
> feat: change to stone-12-1

- CHANGELOG.md
- src/lib/layout/navbar/utils.ts
- src/lib/pages/publish-module/publish.tsx
> fix(components): add republish to  publish module page

- CHANGELOG.md
- src/lib/components/MobileGuard.tsx
- src/lib/components/modal/NoMobile.tsx
> fix(components): revise mobile guard text

- CHANGELOG.md
- src/lib/utils/contractState.test.ts
- src/lib/utils/contractState.ts
- support contract state's key as object, tuple
> Support contract state's key as object, tuple to main

- CHANGELOG.md
- src/lib/app-provider/hooks/useBaseApiRoute.ts
- src/lib/hooks/useOpenTab.ts
- src/lib/services/balance.ts
- src/lib/services/balanceService.ts
> fix: refactor balances route

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> [#672 first] feat: mahalo 1

- CHANGELOG.md
- src/lib/services/move/poolService.ts
> fix: total share 0

- CHANGELOG.md
- src/config/chain/sei.ts
> temporarily update sei graphql (to main)

- CHANGELOG.md
- src/lib/pages/home/index.tsx
> :temp hide sei blocktime

- CHANGELOG.md
- src/lib/components/modal/account/SaveNewAccount.tsx
- src/lib/pages/saved-accounts/index.tsx
> fix: save account hex duplicate and search with hex

- CHANGELOG.md
- src/config/chain/initia.ts
> fix: stone-12-1-nft

- CHANGELOG.md
- src/lib/pages/account-details/components/AccountHeader.tsx
> fix(components): disable save account in mobile

- CHANGELOG.md
- src/lib/hooks/useExecuteCmds.ts
> fix: exeucte msg regex for sylvia contract

- CHANGELOG.md
- src/lib/components/copy/CopyButton.tsx
- src/lib/components/copy/CopyTemplate.tsx
- src/lib/components/table/modules/ModulesTableRow.tsx
- src/lib/layout/Searchbar.tsx
- src/lib/pages/account-details/components/resources/ResourceLeftPanel.tsx
- src/lib/pages/account-details/components/resources/ResourceSectionBody.tsx
- src/lib/pages/home/components/DevShortcut.tsx
- src/lib/pages/module-details/components/ModuleTop.tsx
> fix(components): fix bug bash related to resource and module

- CHANGELOG.md
- src/lib/app-provider/hooks/useGetSigningClient.ts
> fix: client undefined

- CHANGELOG.md
- src/lib/pages/contract-details/index.tsx
- src/lib/pages/module-details/components/tables/ModuleRelatedProposalsTable.tsx
- src/lib/pages/module-details/components/tables/history/index.tsx
- src/lib/pages/module-details/components/tables/index.tsx
- src/lib/services/move/moduleService.ts
> Fix: bug in cut release

- CHANGELOG.md
- package.json
> Update docs for releasing v1.4.1

- CHANGELOG.md
- src/lib/amplitude/types.ts
- src/lib/pages/contracts/components/RecentContractsTable.tsx
- src/lib/pages/contracts/data.ts
- src/lib/pages/contracts/index.tsx
- src/lib/query/contract.ts
- src/lib/services/contract.ts
- src/lib/services/contractService.ts
> feat: api v1 recent contracts

- CHANGELOG.md
- src/config/chain/sei.ts
- update Sei testnet's indexer
> update sei indexer to prod

- CHANGELOG.md
- src/config/chain/sei.ts
> chore: change sei's indexer back

- CHANGELOG.md
- src/lib/pages/query/components/JsonQuery.tsx
- src/lib/pages/query/index.tsx
- src/lib/services/contractService.ts
> fix: flicker query page

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> feat: add initia testnet 13 support

- CHANGELOG.md
- src/lib/pages/block-details/components/BlockDetailsTop.tsx
- src/lib/pages/block-details/components/BlockTxsTable.tsx
> fix(components): add missing title for block txs in block detail

- CHANGELOG.md
- src/lib/services/contract.ts
> fix: contract lists nullable fields

- CHANGELOG.md
- src/lib/hooks/index.ts
- src/lib/hooks/useDebounce.ts
- src/lib/pages/account-details/components/nfts/NftsByCollection.tsx
- src/lib/pages/nft-collection-details/components/CollectionSupplies.tsx
- src/lib/pages/nft-collection-details/components/tables/activities/index.tsx
- src/lib/pages/nft-collections/components/Collections.tsx
- src/lib/pages/past-txs/index.tsx
- src/lib/pages/pools/components/supportedSection/index.tsx
- src/lib/pages/pools/components/unsupportedSection/index.tsx
- src/lib/pages/proposals/index.tsx
> fix: add useDebounce on searching

- CHANGELOG.md
- package.json
- src/config/chain/initia.ts
> Update docs for cutting release 1.5.0

- CHANGELOG.md
- src/lib/pages/nft-details/components/MintInfo.tsx
- src/lib/pages/nft-details/index.tsx
- src/lib/query/nft.ts
- src/lib/services/nft/nft.ts
> fix: nft minter

- CHANGELOG.md
- src/lib/components/MobileGuard.tsx
- src/lib/components/table/proposals/ProposalsTableMobileCard.tsx
- src/lib/layout/mobile/NavDrawer.tsx
- src/lib/pages/proposals/index.tsx
> feat(components): add mobile view for proposal list

- CHANGELOG.md
- src/lib/model/account.ts
- src/lib/pages/account-details/components/tables/txs/index.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/components/ErrorFetchingDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/components/index.ts
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lockup/MsgLockTokensDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolAssetsGrid.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/lp/components/PoolLPCard.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/superfluid/MsgLockAndSuperfluidDelegateDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/MsgSwapExactAmountInDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/MsgSwapExactAmountOutDetail.tsx
- src/lib/pages/pools/components/pool-details/tables/pool-txs/messages/swap/components/PoolSwap.tsx
- src/lib/pages/pools/index.tsx
- src/lib/pages/pools/poolId.tsx
- src/lib/pages/tx-details/components/MessageSection.tsx
- src/lib/services/txService.ts
- src/lib/utils/tx/__test__/extractTxLogs.example.ts
- src/lib/utils/tx/extractTxLogs.ts
- proposal events
- account tx error
> fix: osmosis pool events

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/pages/account-details/components/resources/ResourceLeftPanel.tsx
- src/lib/pages/account-details/components/resources/ResourceSection.tsx
- src/lib/pages/account-details/components/resources/ResourceSectionBody.tsx
> fix: initia

- CHANGELOG.md
- src/lib/amplitude/types.ts
- src/lib/app-provider/hooks/useBaseApiRoute.ts
- src/lib/layout/mobile/NavDrawer.tsx
- src/lib/pages/codes/components/RecentCodesTable.tsx
- src/lib/pages/codes/data.ts
- src/lib/pages/codes/index.tsx
- src/lib/query/code.ts
- src/lib/services/code.ts
- src/lib/services/codeService.ts
- src/lib/services/publicProjectService.ts
> feat: api v1 code list

- CHANGELOG.md
- src/lib/components/MobileGuard.tsx
> fix: mobile guard

- CHANGELOG.md
- src/lib/query/proposal.ts
- src/lib/services/proposal.ts
- src/lib/services/proposalService.ts
> feat: api v1 - proposal type filter

- CHANGELOG.md
- next.config.js
> feat: redirect from usei to homepage

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/lib/amplitude/types.ts
- src/lib/components/table/proposals/StatusChip.tsx
- src/lib/components/table/proposals/__stories__/StatusChip.stories.ts
- src/lib/pages/proposal-details/components/proposal-overview/__stories__/StatusSummary.stories.ts
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/ActiveDot.tsx
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/Countdown.tsx
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/SummaryStatusBody.tsx
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/SummaryStatusChip.tsx
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/index.tsx
- src/lib/pages/proposal-details/components/proposal-top/index.tsx
- src/lib/pages/proposal-details/data.ts
- src/lib/pages/proposal-details/index.tsx
- src/lib/pages/proposal-details/utils.ts
- src/lib/services/proposal.ts
- src/lib/services/proposalService.ts
- src/lib/types/proposal.ts
- src/lib/utils/assetValue.ts
- src/lib/utils/formatter/formatTokenWithValue.test.ts
- src/lib/utils/formatter/formatTokenWithValue.ts
> [After #763] Feat/status summary body

- CHANGELOG.md
- src/lib/pages/pools/components/pool-details/header/PoolInfo.tsx
> fix(components): add relevant contract to cosmwasm pool

- CHANGELOG.md
- src/lib/pages/proposal-details/components/vote-details/voting-period/votes-table/index.tsx
> fix: proposal votes pagination, scrolling

- CHANGELOG.md
- src/lib/pages/pools/index.tsx
> fix: pool list overlay

- src/lib/components/table/proposals/StatusChip.tsx
- src/lib/types/proposal.ts
> fix: cancelled status

- CHANGELOG.md
- src/config/chain/initia.ts
- src/config/chain/osmosis.ts
- src/config/chain/sei.ts
- src/config/chain/stargaze.ts
- src/config/chain/terra.ts
- src/config/chain/types.ts
- src/lib/pages/proposal-details/components/proposal-top/ViewProposalJson.tsx
- src/lib/pages/proposal-details/components/proposal-top/index.tsx
> fix: proposal view in json

- CHANGELOG.md
- src/lib/pages/proposal-details/components/ResultExplanation.tsx
- src/lib/pages/proposal-details/components/VpPercentThreshold.tsx
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/index.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/VotingResult.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/VotingThreshold.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx
> feat: vote result vote details section

- CHANGELOG.md
- src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/DepositOverview.tsx
- src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/VotingOverview.tsx
- src/lib/pages/proposal-details/components/vote-details/VoteDetailsAccordionItem.tsx
- src/lib/pages/proposal-details/components/vote-details/deposit-period/DepositPeriodSection.tsx
- src/lib/pages/proposal-details/components/vote-details/index.tsx
- src/lib/pages/proposal-details/index.tsx
- src/lib/pages/proposal-details/types.ts
> fix: vote internal

- CHANGELOG.md
- src/lib/components/asset/SupportedAssetTitle.tsx
- src/lib/components/asset/UnsupportedAssetTitle.tsx
- src/lib/components/table/TableTitle.tsx
- src/lib/pages/proposal-details/components/proposal-overview/ProposalMessages.tsx
> fix(components): add empty state for proposal msgs

- CHANGELOG.md
- src/config/chain/osmosis.ts
- src/config/chain/sei.ts
- src/config/chain/stargaze.ts
- src/config/chain/terra.ts
- src/config/chain/types.ts
> feat: config single staking

- CHANGELOG.md
- src/config/chain/osmosis.ts
> feat: temp osmo graphql

- CHANGELOG.md
- src/lib/components/token/TokenImageRender.tsx
- src/lib/icon/NAToken.tsx
- src/lib/pages/pools/components/supportedSection/AllocationBadge.tsx
> fix: fallback na icon

- src/config/chain/neutron.ts
- src/config/chain/osmosis.ts
> fix: update gql

- CHANGELOG.md
- src/config/chain/neutron.ts
> feat: pion-1 gql prod

- CHANGELOG.md
- src/config/chain/neutron.ts
> feat: neutron-1 prod

- src/config/chain/neutron.ts
> fix: neutron 1 legacy

- CHANGELOG.md
- src/lib/components/Tooltip.tsx
- src/lib/components/action-msg/ActionMessages.tsx
- src/lib/components/action-msg/MultipleActionsMsg.tsx
- src/lib/components/action-msg/SingleMsg.tsx
- src/lib/components/table/transactions/TransactionsTableMobileCard.tsx
- src/lib/components/table/transactions/TransactionsTableRow.tsx
- src/lib/pages/home/components/CardInfo.tsx
- src/lib/pages/proposal-details/components/proposal-overview/ProposalMessageCard.tsx
- src/lib/pages/proposal-details/components/proposal-overview/status-summary/SummaryStatusTime.tsx
- src/lib/pages/validators/components/validators-table/ValidatorsTableHeader.tsx
> fix: misc bugs

- src/config/chain/terra.ts
> fix: terra gql

- CHANGELOG.md
- src/config/chain/initia.ts
- src/config/chain/neutron.ts
- src/config/chain/types.ts
- src/lib/model/account.ts
- src/lib/pages/account-details/index.tsx
- src/lib/pages/contract-details/index.tsx
- src/lib/services/delegationService.ts
> fix: disable contract delegations on nongov

- src/config/chain/neutron.ts
- src/config/chain/terra.ts
> fix: new gql

- CHANGELOG.md
- src/lib/pages/proposal-details/components/ResultExplanation.tsx
> fix: proposal rejected explanation

- CHANGELOG.md
- src/lib/pages/contract-details/components/contract-states/index.tsx
> fix: edit error fetching msg

- CHANGELOG.md
- src/lib/amplitude/Amplitude.ts
- src/lib/amplitude/types.ts
- src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx
> Add Amplitude tracking on proposal details page

- CHANGELOG.md
- src/lib/pages/proposal-details/components/VoteThresholdBadge.tsx
- src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/VotingOverview.tsx
- src/lib/pages/proposal-details/components/proposal-stepper/utils.ts
- src/lib/pages/proposal-details/components/vote-details/voting-period/VotingQuorum.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/VotingThreshold.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx
- src/lib/pages/proposal-details/index.tsx
> fix: voting period status badge

- CHANGELOG.md
- src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/VotingOverview.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx
> fix: show quorum only voting period

- CHANGELOG.md
- src/lib/amplitude/track-event/trackInteraction.ts
- src/lib/amplitude/types.ts
- src/lib/pages/pools/components/supportedSection/index.tsx
- src/lib/pages/pools/components/unsupportedSection/index.tsx
- src/lib/pages/validator-details/index.tsx
- src/lib/pages/validators/components/ActiveFilter.tsx
- src/lib/pages/validators/components/OrderSelect.tsx
- src/lib/pages/validators/components/validators-table/ValidatorsTableHeader.tsx
- src/lib/pages/validators/index.tsx
> feat: add amp validator list

- CHANGELOG.md
- src/config/chain/osmosis.ts
> fix: mgirate osmosis gql

- CHANGELOG.md
- src/config/chain/initia.ts
- src/config/chain/neutron.ts
- src/config/chain/types.ts
- src/lib/components/ExplorerLink.tsx
- src/lib/components/ValidatorBadge.tsx
- src/lib/pages/validators/components/validators-table/ValidatorsTableMobileCard.tsx
> fix: external validator links

- CHANGELOG.md
- src/lib/pages/proposal-details/components/ResultExplanation.tsx
- src/lib/pages/proposal-details/components/ViewFailedReason.tsx
- src/lib/pages/proposal-details/components/proposal-overview/__stories__/StatusSummary.stories.ts
- src/lib/services/proposal.ts
- src/lib/types/proposal.ts
> feat: failed reason

- CHANGELOG.md
- src/config/chain/terra.ts
> feat: terra gql

- CHANGELOG.md
- src/lib/components/ExplorerLink.tsx
- src/lib/components/Tooltip.tsx
- src/lib/components/ValidatorBadge.tsx
- src/lib/components/forms/SelectInput.tsx
- src/lib/components/table/MobileLabel.tsx
- src/lib/pages/proposal-details/components/proposal-top/ViewProposalJson.tsx
- src/lib/pages/proposal-details/components/proposal-top/index.tsx
- src/lib/pages/proposal-details/components/vote-details/VoteDetailsAccordionItem.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/ProposalVotesPanel.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/ValidatorVotesPanel.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/validator-votes-table/ValidatorVotesTableRow.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/validator-votes-table/index.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/votes-table/ProposalVotesTableRow.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/votes-table/index.tsx
- src/lib/pages/validator-details/components/tables/voted-proposals/VotedProposalsTableMobileCard.tsx
- src/lib/pages/validator-details/components/validator-top/ValidatorStats.tsx
- src/lib/pages/validator-details/index.tsx
- src/lib/pages/validators/components/validators-table/ValidatorsTableHeader.tsx
> fix: bugbash

- src/lib/components/table/proposals/ProposalsTableHeader.tsx
- src/lib/pages/proposal-details/components/vote-details/voting-period/table/Voter.tsx
> Fix(components): fix proposal detail bug bash

- src/lib/utils/abi.ts
> fix: main abi opt bool

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
- src/lib/components/button/NewProposalButton.tsx
- src/lib/layout/Searchbar.tsx
- src/lib/layout/SubHeader.tsx
- src/lib/layout/mobile/NavDrawer.tsx
- src/lib/pages/modules/index.tsx
- src/lib/pages/nft-collections/index.tsx
- src/lib/pages/validator-details/components/performance/RecentBlocksSection.tsx
> fix: tomcat pretty

- CHANGELOG.md
- src/lib/pages/validators/components/validators-table/ValidatorsPercentDivider.tsx
> fix: validator percent

- CHANGELOG.md
- src/config/chain/default.ts
- src/config/chain/initia.ts
- src/config/chain/neutron.ts
- src/config/chain/osmosis.ts
- src/config/chain/sei.ts
- src/config/chain/stargaze.ts
- src/config/chain/terra.ts
- src/config/chain/types.ts
- src/lib/app-provider/hooks/useConfig.ts
> feat: add tier config

- CHANGELOG.md
- src/lib/components/copy/CopyTemplate.tsx
- src/lib/pages/account-details/components/nfts/NftsByCollection.tsx
- src/lib/pages/nft-collection-details/components/CollectionSupplies.tsx
- src/lib/pages/nft-collection-details/index.tsx
- src/lib/pages/nft-collections/components/CollectionCard.tsx
- src/lib/pages/nft-collections/components/Collections.tsx
- src/lib/query/collection.ts
- src/lib/query/nft.ts
- src/lib/services/nft/collection.ts
- src/lib/services/nft/nft.ts
> feat: update collection and nft lists and search

- CHANGELOG.md
- src/lib/components/WasmPageContainer.tsx
Please refer to this Slack thread: https://alleslabs.slack.com/archives/C04C8JCUBGF/p1714388174104559?thread_ts=1713328187.815919&cid=C04C8JCUBGF
> Fix(components): WASM page container text alignment

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> feat: migrate initia 2 to 3

- CHANGELOG.md
- src/lib/components/asset/index.tsx
- src/lib/model/account.ts
- src/lib/pages/account-details/data.ts
- src/lib/pages/contract-details/index.tsx
- src/lib/services/bank/api.ts
- src/lib/services/bank/index.ts
- src/lib/services/bank/lcd.ts
- src/lib/services/tx/index.ts
- src/lib/services/types/bank.ts
- src/lib/services/types/index.ts
> feat: support lite version balances

- CHANGELOG.md
- src/config/chain/osmosis.ts
- src/config/chain/sei.ts
- src/config/chain/stargaze.ts
- src/config/chain/terra.ts
- src/config/chain/types.ts
- src/lib/pages/validator-details/index.tsx
- src/lib/pages/validators/components/validators-table/index.tsx
> [after #918] Feat/use staking denom from lcd

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> Add initiation-1 chain config

- CHANGELOG.md
- src/lib/services/move/module.ts
- src/lib/services/move/moduleService.ts
> fix: add isGov in module details

- CHANGELOG.md
- src/lib/layout/Searchbar.tsx
> fix: mobile main search

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> feat: add gas token

- CHANGELOG.md
- next-env.d.ts
- src/lib/components/action-msg/SingleMsg.tsx
- src/lib/components/table/AccordionTx.tsx
> fix(components): add separator in message tx that contains token

- CHANGELOG.md
- src/lib/services/block/index.ts
- src/lib/services/searchService.ts
> fix: block query in search

- CHANGELOG.md
- src/lib/pages/tx-details/components/tx-message/msg-receipts/renderUtils.tsx
> [CFE-525]: Fix(components): txs details overflow screen

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
> fix: tomcat endpoints

- CHANGELOG.md
- src/lib/components/select-code/CodeSelectSection.tsx
- src/lib/components/tx/modal/ButtonSection.tsx
- src/lib/layout/mobile/utils.ts
- src/lib/pages/account-details/components/tables/txs/Lite.tsx
- src/lib/pages/home/components/DevShortcut.tsx
- src/lib/pages/home/components/QuickMenuLite.tsx
- src/lib/pages/home/components/QuickMenuMobileLite.tsx
- src/lib/pages/publish-module/components/ModulePublishCard.tsx
> Fix: bug bash

- CHANGELOG.md
- src/lib/services/move/poolService.ts
- src/lib/services/publicProjectService.ts
> fix: remove retries

- CHANGELOG.md
- src/lib/components/ExplorerLink.tsx
- src/lib/components/ValidatorBadge.tsx
- src/lib/components/ValidatorImage.tsx
- src/lib/pages/validator-details/components/validator-top/ValidatorTitle.tsx
- src/lib/pages/validator-details/components/validator-top/index.tsx
- src/lib/services/validator/index.ts
- src/lib/services/validator/misc.ts
> fix: empty string moniker

- CHANGELOG.md
- src/lib/services/types/tx.ts
- src/lib/types/account.ts
- src/lib/types/common.ts
- src/lib/types/validator.ts
- src/lib/utils/address.ts
> fix: sign mode multi

- CHANGELOG.md
- src/lib/services/types/tx.ts
> fix: event value null

- CHANGELOG.md
- src/lib/services/types/move/module.ts
> fix: module txs response

- CHANGELOG.md
- src/config/chain/initia.ts
- src/lib/chain-registry/initiatestnet.ts
- src/lib/layout/subheader/utils.ts
> Feat: add Milkyway (glados-1)

- CHANGELOG.md
- src/lib/services/tx/lcd.ts
> fix: txs contract sequencer

- CHANGELOG.md
- src/lib/services/bank/lcd.ts
- src/lib/services/types/bank.ts
> fix: balances pagination null

- src/lib/components/button/NewProposalButton.tsx
- src/lib/pages/deploy/index.tsx
- src/lib/pages/migrate/components/MigrateOptions.tsx
- src/lib/pages/proposal/store-code/index.tsx
- src/lib/pages/proposal/whitelist/index.tsx
- src/lib/pages/stored-codes/index.tsx
- src/lib/pages/upload/upload.tsx
- src/lib/services/types/wasm/code.ts
- src/lib/services/wasm/code/index.ts
> fix: default wasm permissionless

- CHANGELOG.md
- src/lib/layout/search/SearchResultItem.tsx
- src/lib/layout/search/SearchResultItemBody.tsx
- src/lib/layout/search/SearchZeroState.tsx
- src/lib/layout/search/index.tsx
- src/lib/layout/search/utils.ts
- src/lib/services/name/index.ts
- src/lib/services/nft-collection/index.ts
- src/lib/services/nft-collection/sequencer.ts
- src/lib/services/searchService.ts
- src/lib/services/types/nft-collection.ts
> feat: search collection address

- CHANGELOG.md
- src/lib/layout/network-menu/NetworkAccordion.tsx
> fix: network sub gap

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/config/chain/types.ts
- src/lib/app-provider/contexts/app.tsx
- src/lib/app-provider/hooks/index.ts
- src/lib/app-provider/hooks/useChainConfigs.ts
- src/lib/layout/network-menu/NetworkAccordion.tsx
- src/lib/layout/network-menu/NetworkImage.tsx
- src/lib/layout/network-menu/hooks/useNetworkSelector.ts
- src/lib/layout/network-menu/hooks/utils.ts
- src/lib/layout/network-menu/network-card/NetworkCard.tsx
- src/lib/layout/network-menu/network-card/NetworkCardCta.tsx
- src/lib/providers/cosmos-kit/index.tsx
- src/lib/providers/network-guard/index.tsx
- src/lib/providers/store.tsx
- src/lib/stores/chain-config.test.ts
- src/lib/stores/chain-config.ts
- src/lib/stores/root.ts
> Feat: chain config store

- CHANGELOG.md
- src/lib/components/icon/index.tsx
- src/lib/providers/network-guard/index.tsx
- src/lib/stores/network.test.ts
- src/lib/stores/networks.ts
- Remove userKey from network store
- Add unit tests
- Fix icon props
> fix: remove userKey from network store, add tests

- CHANGELOG.md
- src/lib/components/MoveVerifyBadge.tsx
- src/lib/components/PageHeader.tsx
- src/lib/components/button/NewProposalButton.tsx
- src/lib/components/module/ModuleSourceCode.tsx
- src/lib/components/move-verify-section/NotVerifiedDetails.tsx
- src/lib/components/move-verify-section/OutdatedDetails.tsx
- src/lib/components/move-verify-section/VerifiedDetails.tsx
- src/lib/components/move-verify-section/index.tsx
- src/lib/pages/interact/index.tsx
- src/lib/pages/module-details/components/ModuleInfo.tsx
- src/lib/pages/module-details/components/ModuleInfoBody.tsx
- src/lib/pages/module-details/components/ModuleTop.tsx
- src/lib/pages/module-details/index.tsx
- src/lib/pages/modules/components/ModuleVerificationButton.tsx
- src/lib/pages/modules/index.tsx
- src/lib/services/types/verification/move/index.ts
- src/lib/types/move/module.ts
- src/lib/utils/index.ts
- src/lib/utils/move.ts
> fix(components): add module entry point

- CHANGELOG.md
- src/lib/pages/evm-tx-details/components/EvmTxGasReceipt.tsx
- src/lib/pages/evm-tx-details/components/EvmTxInfo.tsx
- src/lib/pages/evm-tx-details/components/EvmTxInfoMobile.tsx
- src/lib/pages/evm-tx-details/components/evm-tx-method/EvmTxMethodAccordion.tsx
- src/lib/pages/evm-tx-details/components/evm-tx-method/EvmTxTransferErc20.tsx
- src/lib/pages/evm-tx-details/data.ts
- src/lib/pages/evm-tx-details/index.tsx
- src/lib/services/block/index.ts
> Support EIP-1559 on EVM Tx details page

- CHANGELOG.md
- src/lib/pages/evm-contract-verify/components/solidity/EvmContractVerifySolidity.tsx
- src/lib/pages/evm-contract-verify/components/solidity/EvmContractVerifySolidityFoundry.tsx
- src/lib/pages/evm-contract-verify/components/solidity/EvmContractVerifySolidityHardhat.tsx
> feat: verify with Hardhat

- src/lib/layout/index.tsx
* feat(layout): add migration banner to layout for initia
* feat: migration banner link and text
* feat: update date
* feat: update timezone
* feat: update banner
* fix: remove comment
---------
> feat(layout): add migration banner to layout for Initia (#1258)

- src/lib/components/editor/moveSyntax.ts
- src/lib/utils/executeTags.ts
Hi, I fixed some spelling issues
> chore: fix spelling issues
