CHANGELOG.md, next.config.js
I noticed that the logger.info function in the [tunnelRoute.ts](https://github.com/getsentry/sentry-javascript/blob/master/packages/nextjs/src/client/tunnelRoute.ts#L20) file is causing an error when Sentry debug is enabled. To prevent this issue from occurring, I have proposed a workaround solution to disabling the logger by setting the `__DEBUG_BUILD__` flag to false via the `__SENTRY_DEBUG__` environment variable.
=> Disable Sentry debug to prevent "logger.info is not a function" error

CHANGELOG.md, src/env.ts, src/lib/model/contract.ts, src/lib/services/code.ts, src/lib/services/contract.ts
- Fix double slash for endpoint `https://lcd-test.osmosis.zone//cosmwasm/wasm/v1/contract/`
- Disable calling endpoint when there is no contract address in contract detail page `https://lcd-test.osmosis.zone//cosmwasm/wasm/v1/contract/`
Note: endpoint from useWallet contains / at the end, so add / to fallback url
=> fix: double slash for endpoint, disable calling endpoint when there is no contract addr

CHANGELOG.md, src/lib/components/modal/UnsupportedTokensModal.tsx, src/lib/utils/formatter/token.ts
Change unsupported modal style and layout
=> fix: change unsupported tokens layout and style

CHANGELOG.md, src/lib/pages/code-details/components/CTASection.tsx, src/lib/pages/code-details/index.tsx
- Show edit button when code name is set.
- Align button section to top
=> fix: show edit button when code name is set and align all buttons to top

CHANGELOG.md, src/lib/services/publicProjectService.ts
When switching from mainnet to testnet in code details page, public project logo should disappear
- Solve by removing `keepPreviousData`
=> fix: remove keepPreviousData

CHANGELOG.md, src/lib/components/links/GitHubLink.tsx, src/lib/components/links/index.ts, src/lib/pages/code-details/index.tsx, src/lib/pages/contract-details/components/ContractTop.tsx, src/lib/services/contract.ts, src/lib/types/projects.ts
Add Github repo name and link to public code and contract detail pages.
=> feat: add github link to public code and contract

CHANGELOG.md, src/lib/app-provider/query-client/index.ts, src/lib/pages/account-details/components/delegations/DelegationsBody.tsx, src/lib/pages/account-details/components/delegations/RadioCard.tsx, src/lib/pages/account-details/components/delegations/TotalCard.tsx, src/lib/pages/account-details/components/delegations/index.tsx, src/lib/pages/account-details/components/tables/TokenCell.tsx, src/lib/pages/account-details/components/tables/bonded/BondedTableRow.tsx, src/lib/pages/account-details/components/tables/bonded/DelegationsTable.tsx, src/lib/pages/account-details/data.ts, src/lib/pages/account-details/type.ts, src/lib/types/asset.ts, src/lib/types/index.ts, src/lib/utils/assetValue.ts
- change osmosis mainnet graphql
=> feat: osmosis graphql

CHANGELOG.md, src/lib/pages/txs/components/TxsTable.tsx
Add data fetching error state to txs page
=> fix: add data fetching error state to txs page

CHANGELOG.md, src/lib/app-provider/query-client/index.ts, src/lib/components/ValidatorBadge.tsx, src/lib/gql/gql.ts, src/lib/gql/graphql.ts, src/lib/pages/block-details/components/BlockInfo.tsx, src/lib/pages/blocks/components/BlocksRow.tsx, src/lib/pages/txs/index.tsx, src/lib/query/block.ts, src/lib/services/blockService.ts, src/lib/types/block.ts
Add block proposer to block list and block details page
=> feat: add block proposer to block list and block details page

CHANGELOG.md, src/lib/components/modal/UnsupportedTokensModal.tsx, src/lib/pages/account-details/components/asset/index.tsx, src/lib/pages/blocks/components/BlocksRow.tsx
Account details page
- card token size
- font size for unsupported token button
Blocks page
- when tx count equal to zero, should render a secondary text color
=> fix: token card, font size, text color in blocks and account details page

CHANGELOG.md, src/lib/components/ValidatorBadge.tsx, src/lib/utils/formatter/index.ts, src/lib/utils/formatter/text.ts
UI avatar for validator not shown when encounter special chars.
Remove all special character including emoji
=> fix: ui avatar for validator not shown when encounter special chars

CHANGELOG.md, src/lib/pages/block-details/index.tsx, src/lib/pages/blocks/index.tsx, src/lib/pages/network-overview/index.tsx, src/lib/pages/txs/index.tsx, src/lib/services/amplitude.tsx
- Add amplitude for landing on the following pages - blocks, block detail, txs, network overview
=> feat: add landing amp on block(s), txs, network overview

CHANGELOG.md, src/lib/components/InputWithIcon.tsx, src/lib/components/button/NewProposalButton.tsx, src/lib/components/pagination/Next.tsx, src/lib/components/pagination/Previous.tsx, src/lib/components/pagination/index.tsx, src/lib/components/table/proposals/Proposer.tsx, src/lib/components/table/proposals/ResolvedHeight.tsx, src/lib/pages/proposals/components/ProposalStatusFilter.tsx, src/lib/pages/proposals/components/ProposalTypeFilter.tsx, src/lib/pages/proposals/index.tsx, src/lib/pages/proposals/table/ProposalTableRow.tsx, src/lib/services/amplitude.tsx
Add amplitude track to proposal list page
- TO_PROPOSAL_LIST
- USE_INPUT (search)
- USE_FILTER_PROPOSALS_STATUS
- USE_FILTER_PROPOSALS_TYPE
- USE_FILTER_MY_PROPOSALS
- USE_CREATE_NEW_PROPOSAL
- USE_COPIER
proposal ID, block height, proposer
- USE_PAGINATION
left, right, page size, current page
- MINTSCAN
to page type, proposal type, proposal status
=> feat: add amplitude to proposal list page and pagination

CHANGELOG.md, src/lib/components/button/NewProposalButton.tsx, src/lib/pages/proposal/components/InitialDeposit.tsx, src/lib/pages/proposal/store-code/index.tsx, src/lib/pages/proposal/whitelist/index.tsx, src/lib/services/proposalService.ts
Add initial deposit to proposal to store code page
=> feat: add initial deposit to proposal to store code page

CHANGELOG.md, src/lib/components/ConnectWalletAlert.tsx, src/lib/components/StickySidebar.tsx, src/lib/components/upload/InstantiatePermissionRadio.tsx, src/lib/pages/proposal/constants.tsx, src/lib/pages/proposal/store-code/index.tsx, src/lib/services/amplitude.tsx
Add amplitude to proposal to store code page
- To proposal to store code page
`TO_PROPOSAL_TO_STORE_CODE`
- Connect wallet with alert box
Connect wallet : Alert box → Click on connect wallet + alert box
`USE_CLICK_WALLET, alert`
- CTA Tool tip : Proposal to Store code: Change net 
`USE_RIGHT_HELPER_PANEL, "proposal-store-code", "change-network"`
- CTA Tool tip : Proposal to Store code : to Deploy contract
`USE_RIGHT_HELPER_PANEL, "proposal-store-code", "to-/deploy"`
- Pin/Unpin
`USE_UNPIN, "proposal-store-code", true`
- Instantiate permission
`USE_INSTANTIATE_PERMISSION, "proposal-store-code", permissionType, emptyAddressesLength, nonEmptyAddressesLength`
- Deposit: Fill # on click
`USE_DEPOSIT_FILL, "proposal-store-code", 500`
- Submit Proposal
`USE_SUBMIT_PROPOSAL, addressesCount, …
=> feat: add amplitude to proposal to store code page

CHANGELOG.md, src/lib/pages/codes/components/MyStoredCodesSection.tsx, src/lib/pages/codes/components/UploadButton.tsx
=> feat: apply initial condition to my stored codes upload button

CHANGELOG.md, src/config/index.ts, src/config/types.ts, src/lib/app-provider/contexts/app.tsx, src/lib/app-provider/hooks/index.ts, src/lib/app-provider/hooks/useFaucetConfig.ts, src/lib/app-provider/hooks/useNetworkChange.ts, src/lib/app-provider/hooks/useSelectChain.ts, src/lib/app-provider/hooks/useWasmConfig.ts, src/lib/app-provider/tx/clearAdmin.ts, src/lib/components/button/FaucetButton.tsx, src/lib/pages/faucet/index.tsx, src/lib/utils/formatter/text.ts
Use faucet info from chain config
=> feat: use faucet info from chain config

CHANGELOG.md, src/lib/components/select-code/CodeSelect.tsx
- Add permission chip to code selection box
=> feat: permission in code select

CHANGELOG.md, src/lib/services/publicProjectService.ts
Fix public project data on the account details and code details page still remains when switching network
=> fix: wrong data shown when switch network

CHANGELOG.md, src/lib/components/ContractSelectSection.tsx, src/lib/components/ExplorerLink.tsx, src/lib/components/PrimaryNameMark.tsx, src/lib/pages/account-details/components/AccountHeader.tsx
=> fix: fix icns names and contract address alignment

CHANGELOG.md, src/lib/components/tx/TxReceiptRender.tsx, src/lib/pages/tx-details/components/tx-message/EventBox.tsx
=> fix: fix event box content clipping and improve animation

CHANGELOG.md, src/lib/pages/pools/components/pool-details/header/index.tsx, src/lib/pages/pools/poolId.tsx
=> feat(components): add breadcrumb to pool id page

CHANGELOG.md, src/lib/components/json-schema/templates/ObjectFieldTemplate.tsx, src/lib/pages/home/index.tsx
- Fix json schema array field default behavior
=> fix: json array field

CHANGELOG.md, src/lib/app-provider/contexts/app.tsx, src/lib/app-provider/contexts/index.ts, src/lib/app-provider/contexts/nav.tsx, src/lib/components/ContractSelectSection.tsx, src/lib/layout/index.tsx, src/lib/pages/code-details/components/json-schema/CodeSchemaSection.tsx, src/lib/pages/home/index.tsx, src/lib/pages/query/components/QueryArea.tsx, src/lib/pages/query/components/SchemaQuery.tsx, src/lib/utils/json.ts, src/pages/_app.tsx
feat: switch to schema tab when available and prefill, expand, and scroll to the prefill msg
=> Switch to schema tab when available and add msg scrolling

CHANGELOG.md, src/lib/components/json-schema/JsonSchemaDrawer.tsx, src/lib/components/json-schema/UploadTemplate.tsx, src/lib/components/json-schema/section/SchemaInputSection.tsx, src/lib/components/json/JsonInput.tsx, src/lib/pages/code-details/components/json-schema/CodeSchemaSection.tsx, src/lib/pages/execute/components/schema-execute/index.tsx, src/lib/pages/pools/components/unsupportedSection/index.tsx, src/lib/pages/query/components/SchemaQuery.tsx
- Fix sometimes select widget input not full
- Fix manual schema upload max lines
- Fix expand/collapse all chevron
=> Fix/input UI schema

CHANGELOG.md, src/lib/components/json-schema/MessageInputContent.tsx, src/lib/components/json-schema/MessageInputSwitch.tsx, src/lib/layout/Searchbar.tsx, src/lib/pages/execute/components/ExecuteArea.tsx, src/lib/pages/instantiate/instantiate.tsx, src/lib/pages/migrate/components/MigrateContract.tsx, src/lib/pages/query/components/QueryArea.tsx, src/lib/services/searchService.ts
fix icns bech32 prefix searchbar display and schema switch highlight
=> fix icns bech32 prefix searchbar display and schema switch highlight

CHANGELOG.md, src/lib/components/json-schema/form/index.tsx, src/lib/components/json-schema/form/templates/FieldTemplate.tsx, src/lib/components/json-schema/form/widgets/SelectWidget.tsx, src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
- Disable simulating fee if input is invalid
- Reset estimated fee after input has been invalid
=> feat: disable estimate fee when input is invalid

CHANGELOG.md, src/config/theme/initia.ts, src/config/theme/sei.ts, src/config/theme/types.ts, src/lib/components/MotionBox.tsx, src/lib/components/state/StateImage.tsx, src/lib/pages/interaction/component/InteractionTypeSwitch.tsx, src/lib/pages/interaction/index.tsx, src/lib/styles/theme/components/button.ts, src/pages/[network]/interaction/index.tsx, src/pages/interaction/index.tsx
=> feat(components): add module interaction page empty state ui

CHANGELOG.md, src/lib/components/select-contract/SelectContractInstantiator.tsx
- add auto focus 
- add "enter" key listener to execute submit function on Contract Selection Modal
=> Improve contract selection

CHANGELOG.md, src/lib/components/ContractCmdButton.tsx, src/lib/components/action-msg/SingleMsg.tsx, src/lib/hooks/useExecuteCmds.ts, src/lib/styles/theme/components/button.ts, src/lib/utils/executeTags.ts
- support undefined execute msg
- fix typo
=> fix: support undefined execute msg

CHANGELOG.md, src/lib/layout/SubHeader.tsx, src/lib/layout/navbar/index.tsx, src/lib/pages/home/index.tsx
=> fix(components): add transition and fix ux writing on dev features

CHANGELOG.md, src/config/chain/initia.ts
Update chain configurations for `stone-10`.
=> Fix: Initia chain config

CHANGELOG.md, src/lib/app-provider/hooks/useNetworkChange.ts
=> fix: selected chain 404

CHANGELOG.md, src/lib/pages/execute/components/JsonExecute.tsx, src/lib/pages/execute/components/schema-execute/ExecuteBox.tsx
- hotfix: add attached funds to code snippet
=> fix: attached funds (to main)

CHANGELOG.md, src/lib/components/WasmPageContainer.tsx
=> fix: add min height to wasm page container to properly align footer

CHANGELOG.md, src/lib/components/button/SubmitButton.tsx, src/lib/components/button/index.ts, src/lib/pages/execute/components/JsonExecute.tsx, src/lib/pages/interact/component/form/ExecuteArea.tsx, src/lib/pages/interact/component/form/ViewArea.tsx, src/lib/pages/query/components/JsonQuery.tsx
=> feat: submit button

CHANGELOG.md, src/lib/components/ExplorerLink.tsx, src/lib/components/table/proposals/ProposalsTableRow.tsx, src/lib/components/tx/modal/ButtonSection.tsx
- fix explorer link for module address
=> fix: support initia module address in link

CHANGELOG.md, src/lib/components/LoadingOverlay.tsx, src/lib/pages/account-details/components/modules/ModuleLists.tsx, src/lib/pages/account-details/components/modules/ModuleListsBody.tsx, src/lib/pages/account-details/index.tsx, src/lib/pages/module-details/components/ModuleTop.tsx, src/lib/pages/tx-details/components/tx-message/EventBox.tsx, src/lib/styles/theme/components/form.ts, src/lib/utils/abi.ts
=> fix: bug overall

CHANGELOG.md, src/lib/components/table/transactions/TransactionsTable.tsx, src/lib/components/table/transactions/TransactionsTableMobileCard.tsx
=> fix(components): remove relation badge from tx card in txs

CHANGELOG.md, src/config/chain/initia.ts, src/lib/chain-registry/initiatestnet.ts, src/lib/services/poolService.ts
=> feat: add stone-12-1 to main

CHANGELOG.md, src/lib/hooks/useQueryCmds.ts
- Fix query msg regex for Sylvia contract
Previous version's response
```
Sylvia: Error parsing into type transmuter::contract::ContractQueryMsg: Unsupported message received: {\"\":{}}. Messages supported by this contract: calc_in_amt_given_out, calc_out_amt_given_in, get_admin, get_admin_candidate, get_share_denom, get_shares, get_swap_fee, get_total_pool_liquidity, get_total_shares, is_active, spot_price: query wasm contract failed: invalid request
```
New version's response
```
Sylvia: Error parsing into type transmuter::contract::ContractQueryMsg: Unsupported message received: {\"\":{}}. Messages supported by this contract: calc_in_amt_given_out, calc_out_amt_given_in, get_admin, get_admin_candidate, get_share_denom, get_shares, get_swap_fee, get_total_pool_liquidity, …
```
=> fix: query msg regex for Sylvia contract

CHANGELOG.md, src/lib/components/table/contracts/ContractsTableMobileCard.tsx, src/lib/pages/contract-details/components/ContractTop.tsx, src/lib/pages/contract-details/components/contract-states/StateLoader.tsx, src/lib/pages/upload/completed.tsx
=> fix(components): fix contract card and states ui

CHANGELOG.md, src/lib/components/LabelText.tsx, src/lib/pages/pools/components/supportedSection/PoolCard.tsx, src/lib/types/pool.ts
=> fix: reroute cosmwasm pool back to pool detail page

CHANGELOG.md, src/config/chain/initia.ts, src/config/chain/types.ts, src/lib/components/module/ModuleSourceCode.tsx, src/lib/pages/module-details/index.tsx, src/lib/services/move/module.ts, src/lib/services/move/moduleService.ts
=> feat: mahalo module verify

CHANGELOG.md, src/lib/components/CustomTab.tsx, src/lib/pages/modules/components/RecentModulesTable.tsx, src/lib/pages/modules/index.tsx
=> fix: bug bash

CHANGELOG.md, README.md, src/lib/components/button/InstantiateButton.tsx, src/lib/components/forms/AssetInput.tsx, src/lib/components/fund/selectFund.tsx, src/lib/components/json-schema/UploadTemplate.tsx, src/lib/components/select-contract/ContractListDetail.tsx, src/lib/components/select-contract/SelectContractAdmin.tsx, src/lib/components/upload/InstantiatePermissionRadio.tsx, src/lib/components/upload/UploadSection.tsx, src/lib/pages/admin/index.tsx, src/lib/pages/contract-details/components/contract-states/StateLoader.tsx, src/lib/pages/faucet/index.tsx, src/lib/pages/instantiate/component/Footer.tsx, src/lib/pages/interact/component/drawer/body/ModuleSelectMainBody.tsx, src/lib/pages/migrate/components/MigrateContract.tsx, src/lib/pages/module-details/components/ModuleTop.tsx, src/lib/pages/pools/components/supportedSection/index.tsx, src/lib/pages/proposal/components/Footer.tsx, src/lib/pages/proposal/store-code/index.tsx, src/lib/pages/proposal/whitelist/index.tsx, src/lib/pages/stored-codes/components/UploadButton.tsx, src/lib/services/contractStateService.ts
- Use `isDisabled` instead of `disabled` as props on Button
- Fix contract state next key condition
- Update README.md
=> Fix isDisabled on Button, contract state next key and update readme 

CHANGELOG.md, src/lib/components/table/proposals/ProposalTextCell.tsx, src/lib/components/table/proposals/ProposalsTableMobileCard.tsx, src/lib/components/table/proposals/ProposalsTableRow.tsx, src/lib/pages/proposals/index.tsx, src/lib/services/proposal.ts, src/lib/services/proposalService.ts, src/lib/types/proposal.ts
=> feat: multi-type proposals

CHANGELOG.md, src/lib/utils/contractState.test.ts, src/lib/utils/contractState.ts, src/lib/utils/validate.test.ts, src/lib/utils/validate.ts
=> Support contract state key as base64

CHANGELOG.md, src/lib/utils/fee.test.ts
Add test validation for Fee.ts
=> Fee.ts test validation

CHANGELOG.md, src/lib/utils/format.test.ts
Add unit test for format.test.ts
=> Feature/cfe 329 format.test.ts unit test 

CHANGELOG.md, src/lib/stores/account.test.ts
Add unit test for account store
=> test(utils): add unit test for account store (mobx)

CHANGELOG.md, src/lib/pages/proposal-details/components/VoteQuorumCircle.tsx, src/lib/pages/proposal-details/components/VoteQuorumText.tsx, src/lib/pages/proposal-details/components/VpPercentCard.tsx, src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/VotingOverview.tsx, src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/VotingOverviewQuorum.tsx, src/lib/pages/proposal-details/components/vote-details/index.tsx, src/lib/pages/proposal-details/components/vote-details/voting-period/VotingQuorum.tsx, src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx, src/lib/pages/proposal-details/index.tsx
=> feat: quorum information on vote section

CHANGELOG.md, src/lib/components/Expedited.tsx, src/lib/components/table/proposals/ProposalsTableMobileCard.tsx, src/lib/layout/mobile/NavDrawer.tsx, src/lib/pages/proposal-details/components/VoteThresholdBar.tsx, src/lib/pages/proposal-details/components/proposal-top/index.tsx, src/lib/pages/proposal-details/utils.ts
=> fix: expedited with params

CHANGELOG.md, src/lib/services/account.ts, src/lib/services/asset.ts, src/lib/services/balance.ts, src/lib/services/block.ts, src/lib/services/code.ts, src/lib/services/contract.ts, src/lib/services/contractState.ts, src/lib/services/delegation.ts, src/lib/services/move/module.ts, src/lib/services/move/pool.ts, src/lib/services/move/resource.ts, src/lib/services/nft/collection.ts, src/lib/services/nft/nft.ts, src/lib/services/overview.ts, src/lib/services/proposal.ts, src/lib/services/tx.ts, src/lib/utils/index.ts, src/lib/utils/zod.ts
=> Add logging error in Zod parsing

CHANGELOG.md, src/config/chain/osmosis.ts, src/lib/pages/home/components/CardInfo.tsx
=> fix: overview tooltip

CHANGELOG.md, src/lib/components/Tooltip.tsx
=> fix: pool asset card

CHANGELOG.md, src/lib/components/table/MobileCardTemplate.tsx, src/lib/components/table/ViewMore.tsx, src/lib/pages/blocks/components/BlocksTableHeader.tsx, src/lib/pages/blocks/components/BlocksTableMobileCard.tsx, src/lib/pages/blocks/components/BlocksTableRow.tsx, src/lib/pages/validator-details/components/performance/index.tsx, src/lib/pages/validator-details/components/tables/ProposedBlocksTable.tsx, src/lib/pages/validator-details/components/validator-overview/index.tsx, src/lib/pages/validator-details/index.tsx, src/lib/services/validatorService.ts
=> Validator proposed blocks table

CHANGELOG.md, src/lib/pages/block-details/components/BlockDetailsTop.tsx, src/lib/pages/proposal-details/components/proposal-top/ViewProposalJson.tsx
=> feat: view json block + proposal details

CHANGELOG.md, src/lib/pages/validator-details/components/bonded-token-changes/VotingPowerChart.tsx, src/lib/pages/validator-details/components/validator-overview/index.tsx
=> [CFE-37] Feature: current bonded token link

CHANGELOG.md, src/lib/components/PageContainer.tsx, src/lib/components/PageHeaderContainer.tsx, src/lib/layout/SubHeader.tsx, src/lib/layout/index.tsx, src/lib/pages/validator-details/components/validator-top/index.tsx, src/lib/pages/validator-details/index.tsx, src/lib/pages/validators/index.tsx
=> feat: page header component

CHANGELOG.md, src/lib/components/json-schema/MessageInputSwitch.tsx, src/lib/pages/proposal-details/components/proposal-overview/status-summary/Countdown.tsx
=> fix: voting countdown text

CHANGELOG.md, src/lib/pages/proposal-details/components/proposal-overview/status-summary/Countdown.tsx, src/lib/pages/validator-details/components/tables/voted-proposals/VotedProposalsRow.tsx, src/lib/pages/validator-details/components/tables/voted-proposals/VotedProposalsTableBody.tsx
=> fix: voted proposal freeze columns

CHANGELOG.md, src/lib/components/ExplorerLink.tsx, src/lib/pages/publish-module/publish.tsx
=> fix: minor bug

CHANGELOG.md, src/lib/pages/validators/components/validators-table/ValidatorsTableHeader.tsx, src/lib/pages/validators/components/validators-table/ValidatorsTableMobileCard.tsx
=> fix: validator uptime header

CHANGELOG.md, src/lib/pages/publish-module/components/accordions.tsx, src/lib/pages/publish-module/formConstants.ts, src/lib/pages/publish-module/index.tsx, src/lib/pages/publish-module/utils.ts, src/lib/types/move/module.ts
=> fix: Remove module Arbitrary Policy

CHANGELOG.md, src/lib/services/delegation.ts
=> fix: delegation rewards field

CHANGELOG.md, next-env.d.ts, src/lib/pages/module-details/components/ModuleStructs.tsx, src/lib/pages/module-details/components/module-fns/FunctionTypeSwitch.tsx, src/lib/pages/module-details/components/module-fns/ModuleFunctions.tsx
=> fix(components): add not found state in module detail

CHANGELOG.md, src/lib/pages/block-details/data.ts, src/lib/pages/block-details/lite.tsx, src/lib/services/block/index.ts, src/lib/services/block/lcd.ts, src/lib/services/types/block.ts, src/lib/services/types/validator.ts, src/lib/services/validator/index.ts, src/lib/services/validator/lcd.ts, src/lib/types/addrs.ts, src/lib/types/block.ts, src/lib/types/validator.ts, src/lib/utils/address.ts, src/lib/utils/index.ts, src/lib/utils/validator.ts
=> feat: use consensus address

CHANGELOG.md, src/lib/pages/proposal-details/components/VoteQuorumCircle.tsx, src/lib/pages/proposal-details/components/proposal-overview/ProposalMessages.tsx, src/lib/pages/proposal-details/components/proposal-overview/status-summary/SummaryStatusTime.tsx, src/lib/pages/proposal-details/components/proposal-top/index.tsx, src/lib/pages/proposal-details/components/vote-details/deposit-period/DepositPeriodSection.tsx, src/lib/pages/proposal-details/components/vote-details/deposit-period/depositors-table/DepositorsTableHeader.tsx, src/lib/pages/proposal-details/components/vote-details/deposit-period/depositors-table/DepositorsTableRow.tsx, src/lib/pages/proposal-details/components/vote-details/deposit-period/depositors-table/index.tsx, src/lib/services/proposal/lcd.ts, src/lib/services/types/proposal.ts
=> fix: bugbash proposal lite

CHANGELOG.md, src/lib/hooks/useOpenTab.ts, src/lib/services/distribution/index.ts
=> fix: total value and assets

CHANGELOG.md, src/config/chain/initia.ts, src/config/chain/types.ts, src/lib/pages/proposal-details/components/NoVotingPeriodTally.tsx, src/lib/pages/proposal-details/components/ResultExplanation.tsx, src/lib/pages/proposal-details/components/proposal-overview/proposal-period-overview/VotingOverview.tsx, src/lib/pages/proposal-details/components/proposal-overview/status-summary/index.tsx, src/lib/pages/proposal-details/components/vote-details/voting-period/index.tsx, src/lib/pages/proposal-details/data.ts
=> feat: disable voting tally

CHANGELOG.md, src/lib/pages/module-details/components/ModuleInfo.tsx, src/lib/pages/module-details/components/ModuleInfoBody.tsx, src/lib/pages/module-details/index.tsx, src/lib/services/move/module/api.ts, src/lib/services/move/module/index.ts, src/lib/services/types/move/module.ts, src/lib/types/move/module.ts
=> feat: module info lcd

CHANGELOG.md, src/lib/query/collection.ts, src/lib/query/collectionOld.ts, src/lib/query/nft.ts, src/lib/query/nftOld.ts, src/lib/services/expression/nftExpression.ts, src/lib/services/expression/nftExpressionOld.ts, src/lib/services/nft/collection.ts, src/lib/services/nft/collectionService.ts, src/lib/services/nft/nft.ts, src/lib/services/nft/nftService.ts
=> feat: support both new, old db schema on NFTs & collections

CHANGELOG.md, src/lib/services/types/move/module.ts
=> fix: module txs response

CHANGELOG.md, src/lib/app-provider/contexts/app.tsx, src/lib/app-provider/hooks/index.ts, src/lib/app-provider/hooks/useAllowCustomNetworks.ts, src/lib/app-provider/hooks/useChainConfigs.ts, src/lib/app-provider/hooks/useNetworkChange.ts, src/lib/layout/network-menu/NetworkMenuBody.tsx, src/lib/layout/network-menu/NetworkMenuTop.tsx, src/lib/pages/add-network-manual/index.tsx, src/lib/pages/add-network/index.tsx, src/lib/pages/home/components/DevShortcut.tsx, src/lib/pages/home/components/DevShortcuts.tsx, src/lib/pages/home/components/HomeTop.tsx, src/lib/pages/network-config/index.tsx, src/lib/stores/chain-config.ts
=> feat: disable custom network logic

CHANGELOG.md, src/lib/pages/code-details/index.tsx
=> fix(components): fix document link

CHANGELOG.md, src/lib/components/MoveVerifyBadge.tsx, src/lib/components/table/modules/ModulePathLink.tsx, src/lib/pages/module-details/components/ModuleTop.tsx, src/lib/pages/modules/index.tsx, src/lib/pages/my-module-verifications/data.ts, src/lib/pages/publish-module/completed.tsx
- Fix task status showing as failed when it should be successful on my module verifications
- Disabled on entry points when using on L2 (modules list, after a module is published)
- Update wording in tooltip for the move verification badge
=> fix: bug bash move verification
